apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "english-greeter-deployment"
  namespace: "default"
  labels:
    app: "english-greeter"
spec: # this is where we create the replicaset specs
  replicas: 3
  revisionHistoryLimit: 5
  # # minReadySeconds: 5
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  selector:
    matchLabels:
      app: "english-greeter"
  template: # this is where the pod information starts
    metadata: # I am not setting a name for the pods because the deployment will handle that for me
      labels:
        app: "english-greeter"
    spec:
      # terminationGracePeriodSeconds: 30
      containers:
      - name: "english-greeter-app"
        image: "esuminski/english:broken"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080